name: "My Cool Jekyll Site"
description: "my description"

url: "http://laurin2001.github.io/testJekyllSite"
baseurl: "/testJekyllSite"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true